name: Matrix 2

on:
  workflow_dispatch:

jobs:
  build-test:
    strategy:
      matrix:
        version: [12, 14, 16]
        os: [ubuntu-latest, windows-latest]

    # Without this line, the failing matrix job will prevent other from starting
    continue-on-error: true
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: node-app

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          npm ci
