name: Job's default

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: node-app

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm ci
