name: Matrix 2

on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    # Without this line, the failing matrix job will prevent other from starting
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        version: [14, 16]
        os: ['ubuntu-latest', 'macos-latest']
        experimental: [true]
        include:
          # add matrix strategy with specific configuration
          - version: 12
            experimental: true
          - os: 'windows-latest'
            experimental: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          npm ci
