name: Matrix 2

on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    # Without this line, the failing matrix job will prevent other from starting
    strategy:
      fail-fast: true
      matrix:
        version: [14, 16]
        os: [ubuntu-latest]
        experimental: [false]
        # include:
        #   # add matrix strategy with specific configuration
        #   - version: 12
        #     experimental: true
        #   - os: windows-latest
        #     experimental: true

    continue-on-error: ${{ matrix.experimental }}
    runs-on: ${{ matrix.os }}


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          cd node-app
          npm ci
