name: Events exercices

on:
  # Push
  push:
    branches: 
      # Push 2
      - dev
    # # Push 3
      - '!staging'
    # OR (Push 3)
    # branches-ignore:
    #   - staging
      # Push 4
      - 'feat*'
    # Push 5
    paths:
      - "*.ts"
      # Push 6
      - "node-app/*"
  
  # PR
  pull_request:
    types:
    # PR 1
      - opened
    # PR 2
      - closed

  # Scheduled
  schedule:
    # Scheduled 1
    - '*/5 * * * *'
    # Scheduled 2
    - '30 1-23/3 * * *'
    # Scheduled 3
    - '* 3 * * TUE'

  # Manual
  workflow_dispatch:
    
  

jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)

  second-job:
    runs-on: ubuntu-latest
    # Push & PR 3
    if: ${{github.event_name == 'push'}}

    steps:
      - name: Deploy dummy
        run: echo Deploying now ...
      - name: Finishing Deploy dummy
        run: echo Deployment OK ✅